### ISSUE TITLE
Quien puede ayudarme...mi sitio con SSL

### ISSUE THREAD

**Issue by alejocap** [pablokbs/peladonerd#89]
Estoy creando mi sitio con nginx y ssl
(probe usando el archivo de docker-compose del repositorio y me sucede lo mismo)
server_letsencrypt_1 is up-to-date
server_www_1 is up-to-date
server_www2_1 is up-to-date
Creating server_nginx-proxy_1 ... 
ERROR: for server_nginx-proxy_1  dictionary update sequence element #0 has length 61; 2 is required
ERROR: for nginx-proxy  dictionary update sequence element #0 has length 61; 2 is required
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 455, in up
    get_deps,
  File "/usr/lib/python2.7/site-packages/compose/parallel.py", line 70, in parallel_execute
    raise error_to_reraise
ValueError: dictionary update sequence element #0 has length 61; 2 is required

**Comment by pablokbs** [comment]
Podrias pasar el docker-compose que estás usando? me suena a que puede ser un problema de sintaxis en tu yaml

**Comment by fabdelgado** [comment]
@alejocap hace un tiempo hice un fork de @pablokbs, fijate si esta config te ayuda a montarlo, como dice @pablokbs trata de revisar la sintaxis https://github.com/fabdelgado/nginx-proxy-letsencrypt/blob/master/docker-compose-prod.yml
